name: PR-Trivy-Secret-Scan

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-scan:
    name: Trivy Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensures we have the latest commit for scanning

      - name: Run Trivy Secret Scan (Latest Commit Only)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scanners: 'secret'
          format: 'json'
          output: 'trivy-report.json'

      - name: Upload Secret Scan Report (if secrets found)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-secret-scan-report
          path: trivy-report.json
